name: test_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter_native_splash: ^2.4.0
  shared_preferences: ^2.2.3
  get_it: ^7.7.0
  injectable: ^2.4.2
  flutter_bloc: ^8.1.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  injectable_generator: ^2.6.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  # image_path: "your_path"
  min_sdk_android: 21

flutter_native_splash:
  # color: "#your_color"
  # image: "your_path
  web: false


flutter:
  uses-material-design: true

  assets:
    - assets/
