name: test_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # di
  get_it: ^7.7.0
  injectable: ^2.4.2

  # cache
  shared_preferences: ^2.2.3

  # http
  dio: ^5.4.3+1
  dartz: ^0.10.1


  # ui
  flutter_native_splash: ^2.4.0
  cupertino_icons: ^1.0.6

  # state management
  flutter_bloc: ^8.1.6

  # navigation 
  go_router: ^14.2.0

  # localizations
  easy_localization: ^3.0.7

  # generated
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  # image_path: "your_path"
  min_sdk_android: 21

flutter_native_splash:
  # color: "#your_color"
  # image: "your_path
  web: false


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
